### ISSUE TITLE
Post not working

### ISSUE THREAD

**Issue by SnowBG** [sagaragarwal94/python_rest_flask#2]
Hello there.
I'm trying to make a post with this method, but an error returns:

405 METHOD NOT ALLOWED
{"message": "The method is not allowed for the requested URL."}

**Comment by dirkjbosman** [comment]
Send a "post"-request via postman to: http://127.0.0.1:5000/employees, with the following pasted in the "Body" (With "Raw" and "JSON" selected):

{
    "LastName": "Burke",
    "FirstName": "Noodle",
    "Title": "IT Analyst",
    "ReportsTo": 3,
    "BirthDate": "1987-02-18 00:00:00",
    "HireDate": "2009-08-14 00:00:00",
    "Address": "111 Awesome Ave",
    "City": "Foo",
    "State": "AU",
    "Country": "Lala",
    "PostalCode": "T5K 6BHU",
    "Phone": "+1 (780) 428-9489",
    "Fax": "+1 (780) 428-3457",
    "Email": "noodle@chinookcorp.com"
}


Happy coding!
